# Generated by Django 3.2.25 on 2024-08-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetailHistory',
        ),
    ]
