# Generated by Django 3.2.25 on 2024-08-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_orderdetailhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
