# Generated by Django 3.2.25 on 2024-08-06 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_delete_orderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.orderdetail')),
            ],
        ),
    ]
