# Generated by Django 3.2.25 on 2024-08-06 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetailhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailhistory',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='orderdetailhistory',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='date_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='detail_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='detail_equipment_delivered',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='detail_equipment_rented',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='id_detail',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='id_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='id_service',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
