# Generated by Django 3.2.25 on 2024-08-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20240806_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailhistory',
            name='detail_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
