# Generated by Django 3.2.25 on 2024-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderdetailhistory_detail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetailhistory',
            name='detail_equipment_delivered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
