# Generated by Django 3.2.25 on 2024-08-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderdetailhistory_detail_equipment_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='equipment_undelivered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetailhistory',
            name='detail_equipment_undelivered',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
